# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-12 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0002_auto_20200311_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
